# Generated by Django 2.2.1 on 2019-06-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(max_length=100)),
            ],
        ),
    ]
